-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE "users" (
--     "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     "username" TEXT UNIQUE NOT NULL,
--     "email" TEXT UNIQUE NOT NULL,
--     "password_hash" TEXT NOT NULL,
--     "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
