-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE "categories" (
--     "id" SERIAL PRIMARY KEY,
--     "recipe_id" UUID NOT NULL REFERENCES "recipes"("id") ON DELETE CASCADE,
--     "name" TEXT NOT NULL
-- );
