-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Join Tables
-- CREATE TABLE "recipe_categories" ( "recipe_id" UUID NOT NULL REFERENCES "recipes"("id") ON DELETE CASCADE, "category_id" INTEGER NOT NULL REFERENCES "categories"("id") ON DELETE CASCADE, PRIMARY KEY ("recipe_id", "category_id") );
-- CREATE TABLE "recipe_ingredients" ( "id" SERIAL PRIMARY KEY, "recipe_id" UUID NOT NULL REFERENCES "recipes"("id") ON DELETE CASCADE, "ingredient_id" INTEGER NOT NULL REFERENCES "ingredients"("id") ON DELETE RESTRICT, "quantity" TEXT NOT NULL, "unit" TEXT );
