-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "public"."recipes"
-- ADD COLUMN category_id uuid;  -- or integer, depending on categories.id type;
